apiVersion: v1
kind: ConfigMap
metadata:
  name: player-config
  namespace: default
data: 
  sunbird_instance: "sunbird"
  sunbird_port: "3000"
  sunbird_content_player_url: "https://dev.open-sunbird.org/api/"
  sunbird_learner_player_url: "https://dev.open-sunbird.org/api/"
  sunbird_content_proxy_url: "https://dev.open-sunbird.org/api/"
  sunbird_echo_api_url: "https://staging.open-sunbird.org/api/echo/"
  sunbird_autocreate_trampoline_user: "false"
  sunbird_portal_realm: "sunbird"
  sunbird_portal_auth_server_url: "https://dev.open-sunbird.org/auth"
  sunbird_portal_auth_server_client: "portal"
  sunbird_trampoline_client_id: "trampoline"
  sunbird_trampoline_secret: "36c4277f-d59b-4ea2-b788-964b96bd47d1"
  ekstep_env: "qa"
  sunbird_default_channel: "sunbird-dev"
  sunbird_api_auth_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkMTc1MDIwNDdlODc0ODZjOTM0ZDQ1ODdlYTQ4MmM3MyJ9.7LWocwCn5rrCScFQYOne8_Op2EOo-xTCK5JCFarHKSs"
  sunbird_enable_permission_check: "1"
  sunbird_session_store_type: "cassandra"
  sunbird_dataservice_url: "https://dev.open-sunbird.org/api/"
  sunbird_cassandra_urls: "10.44.0.6:9042"
  sunbird_telemetry_packet_size: "200"
  sunbird_environment: "staging"
  sunbird_android_app_url: "http://www.sunbird.org"
  # sunbird_portal_cdn_url: "https://dev-sunbird-temp.azureedge.net/player/"
  sunbird_portal_title_name: "Sunbird dev"
  sunbird_enable_signup: "true"
  # sunbird_config_service_url: "https://dev-sunbird-temp.azureedge.net/player/"
  sunbird_tenant_cdn_url: "https://staging-sunbird.azureedge.net/tenants"
  sunbird_cloud_storage_urls: "https://s3.ap-south-1.amazonaws.com/ekstep-public-qa/,https://ekstep-public-qa.s3-ap-south-1.amazonaws.com/,https://sunbirdstaging.blob.core.windows.net/sunbird-content-staging/"
