apiVersion: v1
kind: Service
metadata:
  name: player-service
  labels:
    name: player-service
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
      protocol: TCP
  selector:
    app: player
